name: Deploy to Github Pages
on:
  push:
    branches: [main]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      
      - name: Setup .NET SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Publish .NET Core project
        run: dotnet publish WhoAmI/WhoAmI.Web/WhoAmI.Web.csproj -c Release -o release --nologo
      
      - name: Change base tag in index.html from '/' to 'WhoAmI' to match Github Pages repository subdirectory
        run: sed -i 's/<base href="\/" \/>/<base href="\/WhoAmI\/" \/>/g' release/wwwroot/index.html
        
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Commit wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
